import { Inject, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { In, Repository } from 'typeorm';
import { Base62Encoder } from './base62-encoder.provider';
import { QuickLinkDto } from './dto/quicklink.dto';
import { QuickLink } from './quicklink.entity';

@Injectable()
export class QuickLinkService {
  constructor(
    @InjectRepository(QuickLink)
    private readonly quickLinkRepository: Repository<QuickLink>,
    @Inject(Base62Encoder)
    private readonly base62Encoder: Base62Encoder,
  ) {}
  /**
   * It returns a promise that resolves to an array of QuickLink objects
   * @returns An array of QuickLink objects
   */
  async getLinks(): Promise<Array<QuickLink>> {
    return this.quickLinkRepository.find();
  }
  /**
   * It takes an array of links, encodes them, finds the existing links, filters the new links, saves the
   * new links, and returns the new and existing links
   * @param {string[]} links - string[] - The original links that the user entered
   * @returns An array of QuickLink objects.
   */

  async createNewQuickLinks(links: string[]): Promise<QuickLink[]> {
    const encodedLinks = await this.encodeLinks(links);
    const existingLinks = await this.findExistingLinks(encodedLinks);

    const newQuickLinks = this.filterNewLinks(
      links,
      encodedLinks,
      existingLinks,
    );
    const newCreatedLinks = await this.quickLinkRepository.save(newQuickLinks);
    return [...newCreatedLinks, ...existingLinks];
  }

  /**
   * It takes a short link, finds the corresponding quick link in the database, and returns it
   * @param {string} shortLink - string - The short link that we want to find the actual link for.
   * @returns The actual link
   */
  async getActualLink(shortLink: string): Promise<QuickLink> {
    const foundLink = await this.quickLinkRepository.findOne({
      where: {
        shortLink: shortLink,
      },
    });
    if (!foundLink) {
      throw new NotFoundException(`No actual link found for ${shortLink}`);
    }
    return foundLink;
  }
  /**
   * It takes an array of links, encodes each link, and returns an array of encoded links
   * @param {string[]} links - string[] - an array of links to be encoded
   * @returns An array of strings.
   */
  private async encodeLinks(links: string[]): Promise<string[]> {
    const encodedShortLinkPromises = links.map((link) =>
      this.base62Encoder.encode(link),
    );
    return Promise.all(encodedShortLinkPromises);
  }

  /**
   * It takes an array of encoded links and returns an array of quick links
   * @param {string[]} encodedLinks - string[] - An array of encoded links.
   * @returns An array of QuickLink objects
   */
  private async findExistingLinks(
    encodedLinks: string[],
  ): Promise<QuickLink[]> {
    return this.quickLinkRepository.find({
      where: {
        shortLink: In(encodedLinks),
      },
    });
  }

  /**
   * It takes in a list of links, a list of encoded links, and a list of existing links, and returns a
   * list of new links
   * @param {string[]} links - string[] - The links that the user has entered
   * @param {string[]} encodedLinks - string[] - The encoded links that were generated by the encodeLinks
   * function.
   * @param {QuickLink[]} existingLinks - QuickLink[] - this is the list of existing links that we have
   * in the database.
   * @returns An array of QuickLink objects.
   */
  private filterNewLinks(
    links: string[],
    encodedLinks: string[],
    existingLinks: QuickLink[],
  ): QuickLinkDto[] {
    const linksWithEncodedShortLinks = links.map((link, index) => ({
      actualLink: link,
      shortLink: encodedLinks[index],
    }));

    return linksWithEncodedShortLinks.filter((linkWithEncodedShortLink) => {
      return !existingLinks.some(
        (existingLink) =>
          existingLink.shortLink === linkWithEncodedShortLink.shortLink,
      );
    });
  }
}
