CREATE TABLE "quicklinks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shortLink" varchar UNIQUE,
  "actualLink" varchar,
  "userId" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstName" varchar,
  "lastName" varchar,
  "authId" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "auth" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE,
  "username" varchar UNIQUE,
  "password" varchar,
  "roleId" id NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE,
  "description" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

ALTER TABLE "quicklinks" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("authId") REFERENCES "auth" ("id");

ALTER TABLE "auth" ADD FOREIGN KEY ("roleId") REFERENCES "roles" ("id");
