CREATE TABLE "quicklinks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shortLink" varchar UNIQUE,
  "actualLink" varchar,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstName" varchar,
  "lastName" varchar,
  "authId" int NOT NULL,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp
);

CREATE TABLE "auth" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE,
  "username" varchar UNIQUE,
  "password" varchar,
  "roleId" id NOT NULL,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE,
  "description" varchar,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp
);

ALTER TABLE "users" ADD FOREIGN KEY ("authId") REFERENCES "auth" ("id");

ALTER TABLE "roles" ADD FOREIGN KEY ("id") REFERENCES "auth" ("roleId");
