apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-quick-links
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: quick-links
  template:
    metadata:
      labels:
        app: quick-links
    spec:
      containers:
        - name: quick-links
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST }}
            - name: DB_PORT
              value: {{ .Values.env.DB_PORT }}
            - name: DB_USER
              value: {{ .Values.env.DB_USER }}
            - name: DB_PASSWORD
              value: {{ .Values.env.DB_PASSWORD }}
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME }}
            - name: REDIS_HOST
              value: {{ .Values.env.REDIS_HOST }}
            - name: REDIS_PASSWORD
              value: {{ .Values.env.REDIS_PASSWORD }}
